In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

In [7]:
# read_csv() reads the CSV into a DataFrame
df = pd.read_csv('/content/Luxury_Housing_Bangalore.csv')

In [8]:
df.shape

(101000, 18)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

In [13]:
## summary of the dataset
df.describe()
print(df.describe(include='all'))

       Property_ID Micro_Market Project_Name Developer_Name  Unit_Size_Sqft  \
count       101000       101000       101000         101000    90954.000000
unique      100000           48          500             11             NaN
top     PROP024258    Jayanagar  Project_367       Prestige             NaN
freq             2         2176          207           9318             NaN
mean           NaN          NaN          NaN            NaN     5972.274765
std            NaN          NaN          NaN            NaN     1783.397836
min            NaN          NaN          NaN            NaN       -1.000000
25%            NaN          NaN          NaN            NaN     4477.250000
50%            NaN          NaN          NaN            NaN     5990.000000
75%            NaN          NaN          NaN            NaN     7497.000000
max            NaN          NaN          NaN            NaN     8999.000000

       Configuration Ticket_Price_Cr Transaction_Type Buyer_Type  \
count         101000           90981           101000     101000
unique             9           72854                2          5
top            5Bhk+           100.0        Secondary        CXO
freq           11375             278            50506      20340
mean             NaN             NaN              NaN        NaN
std              NaN             NaN              NaN        NaN
min              NaN             NaN              NaN        NaN
25%              NaN             NaN              NaN        NaN
50%              NaN             NaN              NaN        NaN
75%              NaN             NaN              NaN        NaN
max              NaN             NaN              NaN        NaN

       Purchase_Quarter  Connectivity_Score  Amenity_Score  \
count            101000       101000.000000   90910.000000
unique                8                 NaN            NaN
top          2024-03-31                 NaN            NaN
freq              12750                 NaN            NaN
mean                NaN            6.992619       7.503663
std                 NaN            1.731757       1.440758
min                 NaN            4.000031       5.000224
25%                 NaN            5.494526       6.260329
50%                 NaN            6.985805       7.499123
75%                 NaN            8.490000       8.752207
max                 NaN            9.999970       9.999865

         Possession_Status Sales_Channel NRI_Buyer  Locality_Infra_Score  \
count               101000        101000    101000         101000.000000
unique                   3             4         2                   NaN
top     Under construction        Online        no                   NaN
freq                 33769         25411     50516                   NaN
mean                   NaN           NaN       NaN              7.498426
std                    NaN           NaN       NaN              1.443128
min                    NaN           NaN       NaN              5.000013
25%                    NaN           NaN       NaN              6.247954
50%                    NaN           NaN       NaN              7.495614
75%                    NaN           NaN       NaN              8.749824
max                    NaN           NaN       NaN              9.999956

        Avg_Traffic_Time_Min          Buyer_Comments
count          101000.000000                   82713
unique                   NaN                       9
top                      NaN  Great value for money.
freq                     NaN                    9383
mean               67.182921                     NaN
std                30.271611                     NaN
min                15.000000                     NaN
25%                41.000000                     NaN
50%                67.000000                     NaN
75%                93.000000                     NaN
max               119.000000                     NaN

In [14]:
df.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.

In [21]:
df.tail()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [22]:
df.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Buyer_Comments'],
      dtype='object')

In [23]:
## Missing Values
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [24]:
## check for duplicates
df.duplicated().sum()

np.int64(1000)

In [25]:
## check unique Property_IDs
print("Total rows:", df.shape[0])
print("Unique Property_IDs:", df['Property_ID'].nunique())

Total rows: 101000
Unique Property_IDs: 100000

In [26]:
## check unique values for each column
for col in df.columns:
    print(col, ":", df[col].nunique(), "unique values")

Property_ID : 100000 unique values
Micro_Market : 48 unique values
Project_Name : 500 unique values
Developer_Name : 11 unique values
Unit_Size_Sqft : 6001 unique values
Configuration : 9 unique values
Ticket_Price_Cr : 72854 unique values
Transaction_Type : 2 unique values
Buyer_Type : 5 unique values
Purchase_Quarter : 8 unique values
Connectivity_Score : 100000 unique values
Amenity_Score : 90000 unique values
Possession_Status : 3 unique values
Sales_Channel : 4 unique values
NRI_Buyer : 2 unique values
Locality_Infra_Score : 100000 unique values
Avg_Traffic_Time_Min : 105 unique values
Buyer_Comments : 9 unique values

In [27]:
## check Configuration column
df['Configuration'].value_counts()

Configuration
5Bhk+    11375
3Bhk     11332
5BHK+    11291
3bhk     11262
5bhk+    11210
4bhk     11173
4Bhk     11151
3BHK     11136
4BHK     11070
Name: count, dtype: int64

In [ ]:
## check Micro_Market column
df['Micro_Market'].value_counts()

In [28]:
# Problem: same market in different casing

# "Sarjapur Road", "sarjapur road", "SARJAPUR ROAD" — all same

print("Before cleaning:", df['Micro_Market'].nunique(), "unique values")

Before cleaning: 48 unique values

In [29]:
## check Ticket_Price_Cr
df['Ticket_Price_Cr'].head(20)

# need to remove ₹ and Cr and convert to number

0     12.750846039118798
1     16.292151871065954
2     10.517724412961911
3      9.396367494232896
4     15.345392444511946
5               ₹9.82 Cr
6     10.896752354445224
7      9.357538943683888
8     12.299449409872416
9      9.193310278863123
10    15.221823819949362
11     7.384787238631023
12    11.042463301181789
13    15.166285271789972
14    13.851563178884089
15                  70.0
16     9.750864804838619
17     9.045289663266425
18     7.623657466155216
19     9.627966273140629
Name: Ticket_Price_Cr, dtype: object

In [30]:
## check for invalid Unit_Size_Sqft
df[df['Unit_Size_Sqft'] <= 0]

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
145,PROP000146,bellary road,Project_145,Puravankara,-1.0,3Bhk,9.094891145564691,Secondary,Startup Founder,2024-03-31,9.952351,7.824742,Ready to move,Direct,yes,6.690428,78,Loved the amenities!
238,PROP000239,KORAMANGALA,Project_238,Sobha,-1.0,5Bhk+,11.065757877782282,Secondary,Other,2024-06-30,8.900902,NaN,Ready to move,Broker,yes,5.698885,43,Too far from my office.
244,PROP000245,sarjapur road,Project_244,L&T Realty,-1.0,5BHK+,18.42659417975841,Secondary,Startup Founder,2023-09-30,5.045976,7.885277,Under construction,Online,yes,5.766082,102,Connectivity is poor.
289,PROP000290,Yelahanka,Project_289,Sobha,-1.0,4BHK,12.199936011524152,Secondary,CXO,2024-06-30,7.194905,6.825103,Ready to move,NRI Desk,no,9.728299,21,Loved the amenities!
747,PROP000748,sarjapur road,Project_247,Embassy,-1.0,3Bhk,9.448331344653205,Primary,Other,2023-12-31,8.701167,5.982552,Ready to move,Online,yes,8.384907,57,Loved the amenities!
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100069,PROP089998,domlur,Project_497,Godrej,-1.0,5BHK+,5.947726506609008,Secondary,HNI,2024-12-31,5.149795,8.012676,Under construction,Broker,yes,9.011854,39,Great value for money.
100087,PROP019615,jp nagar,Project_114,L&T Realty,-1.0,5BHK+,11.398934559342257,Secondary,Other,2025-03-31,7.907058,9.525587,Launch,NRI Desk,no,6.438825,64,Underpriced for location.
100553,PROP023080,Sarjapur Road,Project_79,Tata Housing,-1.0,4Bhk,11.225770440381915,Secondary,HNI,2023-09-30,7.973186,5.215596,Launch,Broker,yes,6.168787,46,Will buy after possession.
100714,PROP078559,domlur,Project_58,Brigade,-1.0,3Bhk,14.438398287100107,Primary,Startup Founder,2025-03-31,9.061157,9.848616,Under construction,NRI Desk,no,8.069680,68,Great view from 15th floor.
100791,PROP086091,jayanagar,Project_90,Total Environment,-1.0,5Bhk+,13.532688994916752,Secondary,Startup Founder,2024-12-31,8.147344,9.187069,Under construction,Online,yes,8.181466,110,Agent was not responsive.

In [31]:
print("Invalid sqft values:", (df['Unit_Size_Sqft'] <= 0).sum())
print("Values:", df.loc[df['Unit_Size_Sqft'] <= 0, 'Unit_Size_Sqft'].unique())

Invalid sqft values: 505
Values: [-1.]

In [32]:
## check NRI_Buyer column
df['NRI_Buyer'].value_counts()

NRI_Buyer
no     50516
yes    50484
Name: count, dtype: int64

In [34]:
## check Buyer_Comments
df['Buyer_Comments'].value_counts()

Buyer_Comments
Great value for money.         9383
Too far from my office.        9310
Connectivity is poor.          9302
Excellent location!            9246
Great view from 15th floor.    9183
Loved the amenities!           9114
Agent was not responsive.      9105
Underpriced for location.      9076
Will buy after possession.     8994
Name: count, dtype: int64

In [33]:
 ## check Purchase_Quarter
df['Purchase_Quarter'].value_counts()

Purchase_Quarter
2024-03-31    12750
2024-09-30    12683
2023-06-30    12655
2023-09-30    12618
2024-06-30    12608
2024-12-31    12595
2023-12-31    12560
2025-03-31    12531
Name: count, dtype: int64

In [35]:
## make a copy of the dataset before cleaning
df_copy = df.copy()

df_copy.shape

(101000, 18)

In [36]:
df_copy.duplicated().sum()

df_copy = df_copy.drop_duplicates(ignore_index=True)

df_copy.duplicated().sum()

df_copy.shape

(100000, 18)

In [37]:
## Configuration — convert to uppercase
df_copy['Configuration'] = df_copy['Configuration'].str.strip().str.upper()

df_copy['Configuration'].value_counts()

Configuration
5BHK+    33536
3BHK     33377
4BHK     33087
Name: count, dtype: int64

In [38]:
## Micro_Market — convert to title case
df_copy['Micro_Market'] = df_copy['Micro_Market'].str.strip().str.title()

df_copy['Micro_Market'].value_counts()

Micro_Market
Jayanagar            6379
Bannerghatta Road    6374
Jp Nagar             6373
Sarjapur Road        6373
Mg Road              6284
Whitefield           6268
Indiranagar          6263
Kanakapura Road      6235
Bellary Road         6215
Yelahanka            6213
Electronic City      6212
Rajajinagar          6207
Domlur               6181
Hebbal               6172
Hennur Road          6158
Koramangala          6093
Name: count, dtype: int64

In [39]:
## NRI_Buyer — standardize yes/no
df_copy['NRI_Buyer'] = df_copy['NRI_Buyer'].str.strip().str.title()

df_copy['NRI_Buyer'].value_counts()

NRI_Buyer
No     50036
Yes    49964
Name: count, dtype: int64

In [40]:
## strip whitespace from other text columns
df_copy['Developer_Name'] = df_copy['Developer_Name'].str.strip()
df_copy['Buyer_Type'] = df_copy['Buyer_Type'].str.strip()
df_copy['Transaction_Type'] = df_copy['Transaction_Type'].str.strip()
df_copy['Possession_Status'] = df_copy['Possession_Status'].str.strip()
df_copy['Sales_Channel'] = df_copy['Sales_Channel'].str.strip()
df_copy['Buyer_Comments'] = df_copy['Buyer_Comments'].str.strip()

In [41]:
# need to remove ₹ and Cr, then convert to float

df_copy['Ticket_Price_Cr'] = df_copy['Ticket_Price_Cr'].astype(str)
df_copy['Ticket_Price_Cr'] = df_copy['Ticket_Price_Cr'].str.replace('₹', '')
df_copy['Ticket_Price_Cr'] = df_copy['Ticket_Price_Cr'].str.replace('Cr', '')
df_copy['Ticket_Price_Cr'] = df_copy['Ticket_Price_Cr'].str.strip()
df_copy['Ticket_Price_Cr'] = df_copy['Ticket_Price_Cr'].replace('nan', np.nan)

## convert to numeric
df_copy['Ticket_Price_Cr'] = pd.to_numeric(df_copy['Ticket_Price_Cr'], errors='coerce')

df_copy['Ticket_Price_Cr'].dtype

print("Nulls after conversion:", df_copy['Ticket_Price_Cr'].isnull().sum())
print("Negative values:", (df_copy['Ticket_Price_Cr'] < 0).sum())

Nulls after conversion: 9913
Negative values: 5

In [42]:
## Unit_Size_Sqft: replace -1 with NaN
df_copy.loc[df_copy['Unit_Size_Sqft'] <= 0, 'Unit_Size_Sqft'] = np.nan


## Ticket_Price_Cr: replace negative prices with NaN
df_copy.loc[df_copy['Ticket_Price_Cr'] < 0, 'Ticket_Price_Cr'] = np.nan

Invalid sqft after fix: 0
Negative prices after fix: 0

In [43]:
df_copy.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10457
Configuration               0
Ticket_Price_Cr          9918
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10000
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18099
dtype: int64

In [44]:
# Unit_Size_Sqft
df_copy['Unit_Size_Sqft'].median()

df_copy['Unit_Size_Sqft'] = df_copy['Unit_Size_Sqft'].fillna(df_copy['Unit_Size_Sqft'].median())

In [45]:
# Ticket_Price_Cr
df_copy['Ticket_Price_Cr'].median()

df_copy['Ticket_Price_Cr'] = df_copy['Ticket_Price_Cr'].fillna(df_copy['Ticket_Price_Cr'].median())

In [46]:
# Amenity_Score
df_copy['Amenity_Score'].median()

df_copy['Amenity_Score'] = df_copy['Amenity_Score'].fillna(df_copy['Amenity_Score'].median())

In [47]:
## Text column — fill with placeholder
df_copy['Buyer_Comments'] = df_copy['Buyer_Comments'].fillna('No Comment')

## verify all nulls are handled
df_copy.isnull().sum()

Property_ID             0
Micro_Market            0
Project_Name            0
Developer_Name          0
Unit_Size_Sqft          0
Configuration           0
Ticket_Price_Cr         0
Transaction_Type        0
Buyer_Type              0
Purchase_Quarter        0
Connectivity_Score      0
Amenity_Score           0
Possession_Status       0
Sales_Channel           0
NRI_Buyer               0
Locality_Infra_Score    0
Avg_Traffic_Time_Min    0
Buyer_Comments          0
dtype: int64

In [48]:
df_copy.info()

df_copy.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        100000 non-null  object
dtypes: float64(5), int64(1), object(12)
memory usage: 13.7+ MB

,Unit_Size_Sqft,Ticket_Price_Cr,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,6005.247410,12.652246,6.993001,7.503743,7.499378,67.188020
std,1638.257026,7.282516,1.731699,1.366641,1.443286,30.267763
min,3000.000000,0.660000,4.000031,5.000224,5.000013,15.000000
25%,4683.000000,10.265189,5.495535,6.395876,6.249147,41.000000
50%,6004.000000,12.038619,6.986316,7.499766,7.497347,67.000000
75%,7332.000000,13.832409,8.490617,8.615671,8.751793,93.000000
max,8999.000000,100.000000,9.999970,9.999865,9.999956,119.000000

In [49]:
# Feature engg
# Price_Per_Sqft = (Price in rupees) / (Area in sqft)

df_copy['Price_Per_Sqft'] = (df_copy['Ticket_Price_Cr'] * 10000000) / df_copy['Unit_Size_Sqft']
df_copy['Price_Per_Sqft'] = df_copy['Price_Per_Sqft'].round(2)

df_copy['Price_Per_Sqft'].describe()

count    100000.000000
mean      22917.029997
std       15430.395655
min         995.620000
25%       15626.127500
50%       20051.000000
75%       26533.872500
max      324359.390000
Name: Price_Per_Sqft, dtype: float64

In [53]:
df_copy['Purchase_Quarter'].unique()

df_copy['Purchase_Date'] = pd.to_datetime(df_copy['Purchase_Quarter'], errors='coerce')

df_copy['Purchase_Year'] = df_copy['Purchase_Date'].dt.year
df_copy['Purchase_Qtr_Num'] = df_copy['Purchase_Date'].dt.quarter
df_copy['Quarter_Label'] = 'Q' + df_copy['Purchase_Qtr_Num'].astype(str) + ' ' + df_copy['Purchase_Year'].astype(str)

# ----- Drop intermediate column -----

df_copy = df_copy.drop(columns=['Purchase_Date'])

In [51]:
df_copy['Price_Tier'] = pd.cut(
    df_copy['Ticket_Price_Cr'],
    bins=[0, 5, 10, 15, 20, df_copy['Ticket_Price_Cr'].max() + 1],
    labels=['Entry Luxury', 'Mid Luxury', 'Premium', 'Ultra Premium', 'Super Luxury']
)

In [52]:
# np.where(condition, value_if_true, value_if_false)
# useful for calculating percentages later

df_copy['NRI_Flag'] = np.where(df_copy['NRI_Buyer'] == 'Yes', 1, 0)

df_copy['NRI_Flag'].value_counts()

NRI_Flag
0    50036
1    49964
Name: count, dtype: int64

In [54]:
from google.colab import auth
auth.authenticate_user()

df_copy.to_gbq(
    destination_table='luxury_housing.luxury_housing_listings_cleaned',
    project_id='ai-ml-2026',
    if_exists='replace'
)

/tmp/ipykernel_13022/3094762166.py:4: FutureWarning: to_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.to_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.to_gbq
  df_copy.to_gbq(
100%|██████████| 1/1 [00:00<00:00, 10894.30it/s]